### ISSUE TITLE
Exporting has no textures

### ISSUE THREAD

**Issue by ghost** [jordanfb/PicoCADToolKit#6]
Exported via picocad toolkit.

Picocad:
![image](https://github.com/jordanfb/PicoCADToolKit/assets/56374185/5c28d914-fa7e-4da6-81dc-91b785d87695)

Blender:
![image](https://github.com/jordanfb/PicoCADToolKit/assets/56374185/5a6b67b2-00f1-4205-934c-41a7c7dfa226)

**Comment by jordanfb** [comment]
Hi! Just to check — did you export it via the toolkit or the toolbox? Unfortunately the naming scheme is a little confusing but at this point we may be stuck with it. The toolbox is the official pico8 application that exports things to .obj files. The unofficial toolkit is this GitHub repo that (as far as I remember) has no way to export things to blender.

To answer your question though — if you loaded the .obj from the official toolbox in blender you should have UVs but you won’t have any texture applied until you create a material with the correct image. Alternatively if the toolbox exports a .mtl file it’s possible you’ll be able to import that as well? But not certain.
If you want more assistance I recommend joining the official discord https://discord.gg/ZexSFA2Wm9 .

Thanks for reminding me about issues though I should make issues for the few outstanding things I need to work on.

**Comment by ghost** [comment]
Oh im so sorry, I didnt notice they were different projects. Ill try out yours, and your suggestions.
